CREATE OR REPLACE TRIGGER trigger_auditoria
BEFORE INSERT OR DELETE OR UPDATE OF precio_venta
ON MICROPROCESADORES
FOR EACH ROW
BEGIN
	IF UPDATING THEN
		DBMS_OUTPUT.PUT_LINE('ACTUALIZANDO EL PRECIO DE UN MICROPROCESADOR LA TABLA DE AUDITORIA');
		INSERT INTO MICROPROCESADORES_AUDITORIA
		VALUES (:OLD.precio_venta, :NEW.precio_venta, :OLD.marca, :OLD.modelo, SYSDATE);	
	ELSIF INSERTING THEN
		DBMS_OUTPUT.PUT_LINE('INSERTANDO UN NUEVO MICROPROCESADOR EN LA TABLA DE AUDITORIA');
		INSERT INTO MICROPROCESADORES_AUDITORIA
		VALUES (0, :NEW.precio_venta, :NEW.marca, :NEW.modelo, SYSDATE);
	ELSIF DELETING THEN
		DBMS_OUTPUT.PUT_LINE('BORRANDO UN MICROPROCESADOR DE LA TABLA DE AUDITORIA');
		DELETE FROM MICROPROCESADORES_AUDITORIA WHERE marca = :OLD.marca AND modelo = :OLD.modelo;
	ELSE
		RAISE_APPLICATION_ERROR (-20001,'Operación no soportada por el trigger_auditoria');
	END IF;
END;