DROP TABLE ACTUA;
DROP TABLE ALQUILA;
DROP TABLE ACTORES;
DROP TABLE SOCIO;
DROP TABLE EJEMPLAR;
DROP TABLE PELICULA;
DROP TABLE DIRECTOR;
CREATE TABLE DIRECTOR (
  NOMBRE       VARCHAR2(40),
  PRIMARY KEY (NOMBRE),
  NACIONALIDAD VARCHAR2(40)
);
CREATE TABLE PELICULA(
ID           NUMBER        CONSTRAINT pkpelicula PRIMARY KEY,
TITULO       VARCHAR2(40),
PRODUCTORA   VARCHAR2(40),
NACIONALIDAD VARCHAR2(40),
FECHA        DATE,
DIRECTOR     VARCHAR2(40)  CONSTRAINT fkdirector REFERENCES DIRECTOR(NOMBRE)
);
CREATE TABLE EJEMPLAR(
IDPELICULA NUMBER,
NUMERO     NUMBER(2),
ESTADO     VARCHAR2(40),
CONSTRAINT pkejemplar PRIMARY KEY(IDPELICULA, NUMERO),
CONSTRAINT fkejemplar FOREIGN KEY(IDPELICULA) REFERENCES PELICULA(ID)
);

CREATE TABLE SOCIO(
  DNI       VARCHAR2(9),
  NOMBRE    VARCHAR2(30) CONSTRAINT nombrenonulo NOT NULL,
  DIRECCION VARCHAR2(30),
  TELEFONO  VARCHAR2(10),
  AVALADOR  VARCHAR2(10),
PRIMARY KEY(DNI),
  CONSTRAINT fksocio FOREIGN KEY(AVALADOR) REFERENCES SOCIO(DNI)
);
CREATE TABLE ACTORES
(
  NOMBRE       VARCHAR2(30),
  NACIONALIDAD VARCHAR2(30),
  SEXO         VARCHAR2(1),
  CONSTRAINT pkactores PRIMARY KEY(NOMBRE),
  CONSTRAINT checksexo    CHECK (SEXO IN ('H', 'M'))
);

CREATE TABLE ACTUA(
ACTOR        VARCHAR2(30),
IDPELICULA   NUMBER,
PROTAGONISTA VARCHAR2(1) DEFAULT 'N',
CONSTRAINT pkactua PRIMARY KEY(ACTOR, IDPELICULA),
CONSTRAINT checkprotagonista CHECK (PROTAGONISTA IN ('N', 'S'))
);
CREATE TABLE ALQUILA(
DNI              CHAR(9),
IDPELICULA       NUMBER,
NUMERO           NUMBER(2),
FECHA_ALQUILER   DATE,
FECHA_DEVOLUCION DATE,
CONSTRAINT pkalquila PRIMARY KEY(DNI, IDPELICULA, NUMERO, FECHA_ALQUILER),
CONSTRAINT fk1dni    FOREIGN KEY(DNI) REFERENCES SOCIO(DNI),
CONSTRAINT fk2peli   FOREIGN KEY(IDPELICULA, NUMERO) REFERENCES EJEMPLAR(IDPELICULA, NUMERO),
CONSTRAINT checkfechas  CHECK (FECHA_DEVOLUCION > FECHA_ALQUILER)
);		



--Ejercicio1
INSERT INTO SOCIO (DNI,NOMBRE,DIRECCION,TELEFONO,AVALADOR)
VALUES ('20','FRAN','SHUT','34242423','20');
INSERT INTO SOCIO (DNI,NOMBRE,DIRECCION,TELEFONO,AVALADOR)
VALUES ('31','FRAN','SHUT','34242423','20');
INSERT INTO SOCIO (DNI,NOMBRE,DIRECCION,TELEFONO,AVALADOR)
VALUES ('41','FRAN','SHUT','34242423','20');
INSERT INTO SOCIO (DNI,NOMBRE,DIRECCION,TELEFONO,AVALADOR)
VALUES ('34','FRAN','SHUT','34242423','41');

INSERT INTO PELICULA (ID,TITULO,PRODUCTORA,NACIONALIDAD,FECHA,DIRECTOR)
VALUES (12,'STARS','TOEI','JAPON','20001212','ALSAFIR');
INSERT INTO PELICULA (ID,TITULO,PRODUCTORA,NACIONALIDAD,FECHA,DIRECTOR)
VALUES (13,'STARS2','TOEXI','TAIWAN','20011212','ALSAFIR');
INSERT INTO PELICULA (ID,TITULO,PRODUCTORA,NACIONALIDAD,FECHA,DIRECTOR)
VALUES (14,'STARS3','TOETI','COREA','20021212','REMIRO');
INSERT INTO PELICULA (ID,TITULO,PRODUCTORA,NACIONALIDAD,FECHA,DIRECTOR)
VALUES (15,'STARS4','TOEZI','CHINA','20031212','REMIRO');

INSERT INTO  DIRECTOR (NOMBRE,NACIONALIDAD)
VALUES ('ALSAFIR','ISRAEL');
INSERT INTO  DIRECTOR (NOMBRE,NACIONALIDAD)
VALUES ('REMIRO','INGLES');


INSERT INTO EJEMPLAR (IDPELICULA,NUMERO,ESTADO)
VALUES (12,1,'CERRADO');
INSERT INTO EJEMPLAR (IDPELICULA,NUMERO,ESTADO)
VALUES (12,2,'ABIERTO');

INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('JUAN','ES','H');
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('ROSA','ES','M');
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('LACIA','ES','M');
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('MACIA','ES','M');
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('ESTANCIA','ES','H');
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('RANCIA','ES','H');

INSERT INTO ACTUA (ACTOR,IDPELICULA,PROTAGONISTA) 
VALUES ('JUAN',12,'S');
INSERT INTO ACTUA (ACTOR,IDPELICULA,PROTAGONISTA) 
VALUES ('ROSA',13,'S');
INSERT INTO ACTUA (ACTOR,IDPELICULA,PROTAGONISTA) 
VALUES ('LACIA',14,'S');
INSERT INTO ACTUA (ACTOR,IDPELICULA,PROTAGONISTA) 
VALUES ('ROSA',15,'N');
INSERT INTO EJEMPLAR (IDPELICULA,NUMERO,ESTADO)
VALUES (12,1,'Cerrado');
INSERT INTO EJEMPLAR (IDPELICULA,NUMERO,ESTADO)
VALUES (12,2,'ABIERTO');
--Ejercicio 2-b
INSERT INTO SOCIO (DNI,DIRECCION,TELEFONO,AVALADOR)
VALUES ('41','SHUT','34242423','20');
INSERT INTO PELICULA (ID,PRODUCTORA,NACIONALIDAD,FECHA,DIRECTOR)
VALUES (12,'TOEI','JAPON','20001212','ALSAFIR');
--c
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('JUAN','ES','X');
--d
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD)
VALUES ('JUAN','ES',);
--Por defecto da error
--e
INSERT INTO ALQUILA (DNI,IDPELICULA,NUMERO,FECHA_ALQUILER,FECHA_DEVOLUCION)
VALUES ('20',12,1,20000323,19990223);
--Eso provoca un error
--f
UPDATE DIRECTOR
SET NACIONALIDAD='USA';
--Esto cambia la nacionalidad  a todos los directores
--g
UPDATE ACTORES
SET NACIONALIDAD='USA'
WHERE NACIONALIDAD='ES';
--Esto cambia la nacionalidad a  todos los actores 
--que tengan la nacionalidad 'ES' a 'USA'
--h
UPDATE SOCIO
SET AVALADOR=null , AVALADOR=20
WHERE AVALADOR=20;
--i
DELETE FROM SOCIO WHERE TELEFONO<5;
--No borra ninguno porque todos los numeros de telefono que hay
--son de varias cifras y por lo tanto son mayores a 5 y no les afecta
--el delete
--j
DELETE FROM SOCIO WHERE TELEFONO>5;
--Como todos loos nmeros son cifras superiores a a 5 se eliminan todos los telefonos
--k
--con solo poner en la condicion el numero especifico a eliminar
--se arreglarian los problemas
DELETE FROM SOCIO WHERE TELEFONO='123232';
--l
DELETE FROM DIRECTOR:
--No se eliminan porque tiene una foreign key en pelicula.
--m
DELETE FROM PELICULA WHERE ID=12;
DELETE FROM PELICULA WHERE ID=13;
--No se eliminarian porque la pelicula esta referenciada en otras tablas,
--Asi que para hacerlo bien el diseño fisico se fuese arreglado con
-- un DELETE ON CASCADE
