--Ejercicio1
INSERT INTO SOCIO (DNI,NOMBRE,DIRECCION,TELEFONO,AVALADOR)
VALUES ('20','FRAN','SHUT','34242423','20');
INSERT INTO SOCIO (DNI,NOMBRE,DIRECCION,TELEFONO,AVALADOR)
VALUES ('31','FRAN','SHUT','34242423','20');
INSERT INTO SOCIO (DNI,NOMBRE,DIRECCION,TELEFONO,AVALADOR)
VALUES ('41','FRAN','SHUT','34242423','20');
INSERT INTO SOCIO (DNI,NOMBRE,DIRECCION,TELEFONO,AVALADOR)
VALUES ('34','FRAN','SHUT','34242423','41');

INSERT INTO PELICULA (ID,TITULO,PRODUCTORA,NACIONALIDAD,FECHA,DIRECTOR)
VALUES (12,'STARS','TOEI','JAPON','20001212','ALSAFIR');
INSERT INTO PELICULA (ID,TITULO,PRODUCTORA,NACIONALIDAD,FECHA,DIRECTOR)
VALUES (13,'STARS2','TOEXI','TAIWAN','20011212','ALSAFIR');
INSERT INTO PELICULA (ID,TITULO,PRODUCTORA,NACIONALIDAD,FECHA,DIRECTOR)
VALUES (14,'STARS3','TOETI','COREA','20021212','REMIRO');
INSERT INTO PELICULA (ID,TITULO,PRODUCTORA,NACIONALIDAD,FECHA,DIRECTOR)
VALUES (15,'STARS4','TOEZI','CHINA','20031212','REMIRO');

INSERT INTO  DIRECTOR (NOMBRE,NACIONALIDAD)
VALUES ('ALSAFIR','ISRAEL');
INSERT INTO  DIRECTOR (NOMBRE,NACIONALIDAD)
VALUES ('REMIRO','INGLES');


INSERT INTO EJEMPLAR (IDPELICULA,NUMERO,ESTADO)
VALUES (12,1,'CERRADO');
INSERT INTO EJEMPLAR (IDPELICULA,NUMERO,ESTADO)
VALUES (12,2,'ABIERTO');

INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('JUAN','ES','H');
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('ROSA','ES','M');
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('LACIA','ES','M');
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('MACIA','ES','M');
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('ESTANCIA','ES','H');
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('RANCIA','ES','H');

INSERT INTO ACTUA (ACTOR,IDPELICULA,PROTAGONISTA) 
VALUES ('JUAN',12,'S');
INSERT INTO ACTUA (ACTOR,IDPELICULA,PROTAGONISTA) 
VALUES ('ROSA',13,'S');
INSERT INTO ACTUA (ACTOR,IDPELICULA,PROTAGONISTA) 
VALUES ('LACIA',14,'S');
INSERT INTO ACTUA (ACTOR,IDPELICULA,PROTAGONISTA) 
VALUES ('ROSA',15,'N');
INSERT INTO EJEMPLAR (IDPELICULA,NUMERO,ESTADO)
VALUES (12,1,'Cerrado');
INSERT INTO EJEMPLAR (IDPELICULA,NUMERO,ESTADO)
VALUES (12,2,'ABIERTO');
--Ejercicio 2-b
INSERT INTO SOCIO (DNI,DIRECCION,TELEFONO,AVALADOR)
VALUES ('41','SHUT','34242423','20');
INSERT INTO PELICULA (ID,PRODUCTORA,NACIONALIDAD,FECHA,DIRECTOR)
VALUES (12,'TOEI','JAPON','20001212','ALSAFIR');
--c
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD,SEXO)
VALUES ('JUAN','ES','X');
--d
INSERT INTO ACTORES (NOMBRE,NACIONALIDAD)
VALUES ('JUAN','ES',);
--Por defecto da error
--e
INSERT INTO ALQUILA (DNI,IDPELICULA,NUMERO,FECHA_ALQUILER,FECHA_DEVOLUCION)
VALUES ('20',12,1,20000323,19990223);
--Eso provoca un error
--f
UPDATE DIRECTOR
SET NACIONALIDAD='USA';
--Esto cambia la nacionalidad  a todos los directores
--g
UPDATE ACTORES
SET NACIONALIDAD='USA'
WHERE NACIONALIDAD='ES';
--Esto cambia la nacionalidad a  todos los actores 
--que tengan la nacionalidad 'ES' a 'USA'
--h
UPDATE SOCIO
SET AVALADOR=null , AVALADOR=20
WHERE AVALADOR=20;
--i
DELETE FROM SOCIO WHERE TELEFONO<5;
--No borra ninguno porque todos los numeros de telefono que hay
--son de varias cifras y por lo tanto son mayores a 5 y no les afecta
--el delete
--j
DELETE FROM SOCIO WHERE TELEFONO>5;
--Como todos loos nmeros son cifras superiores a a 5 se eliminan todos los telefonos
--k
--con solo poner en la condicion el numero especifico a eliminar
--se arreglarian los problemas
DELETE FROM SOCIO WHERE TELEFONO='123232';
--l
DELETE FROM DIRECTOR:
--No se eliminan porque tiene una foreign key en pelicula.
--m
DELETE FROM PELICULA WHERE ID=12;
DELETE FROM PELICULA WHERE ID=13;
--No se eliminarian porque la pelicula esta referenciada en otras tablas,
--Asi que para hacerlo bien el diseño fisico se fuese arreglado con
-- un DELETE ON CASCADE
