CREATE TABLE EmpresaSeguridad(
	cifseguridad varchar(15),
	PRIMARY KEY (cifseguridad)
	);
CREATE TABLE Guardias(
	idguardia   number(5),
	nombre  varchar2(30),
	apellidos   varchar2(30),
	cifseguridad varchar2(15),
	PRIMARY KEY (idguardia),
	FOREIGN KEY (cifseguridad) REFERENCES EmpresaSeguridad
	);
CREATE SEQUENCE secuenciaGuardias START with 1 INCREMENT BY 1 maxvalue 99999999 minvalue 1;
CREATE TABLE SUCURSAL (
	codsucursal number(4), 
	direccion   varchar2(30),
	telefono    varchar2(30),
	ciudad  varchar2(30),
	provincia   varchar2(30),
	cifseguridad varchar2(15),
	FOREIGN KEY (cifseguridad) REFERENCES EmpresaSeguridad,
	PRIMARY KEY (codsucursal)
	);
CREATE SEQUENCE secuenciaSucursal START with 1 INCREMENT BY 1 maxvalue 99999999 minvalue 1;
CREATE TABLE EMPLEADO(
	idtrabajador    number(5),
	nif varchar2(9),
	nombre  varchar2(30),
	apellido    varchar2(30),
	telefono    varchar2(30),
	direccion   varchar2(30),
	codigo_sucursal number(4),
	FOREIGN KEY (codigo_sucursal) REFERENCES SUCURSAL,
	PRIMARY KEY (idtrabajador)
	);
CREATE SEQUENCE secuenciaEmpleado START with 1 INCREMENT BY 1 maxvalue 99999999 minvalue 1;
CREATE TABLE REVISTA(
    idrevista   number(5),
    título  varchar2(30),
    tipo    varchar2(30),
    periodicidad    date,
    PRIMARY KEY (idrevista)
	);
CREATE SEQUENCE secuenciaRevista START with 1 INCREMENT BY 1 maxvalue 99999999 minvalue 1;
CREATE TABLE SucursalPublicaRevista(
    codsucursal	number(4),
    idrevista	number(5),
    FOREIGN KEY (idrevista) REFERENCES REVISTA,
	FOREIGN KEY (codsucursal) REFERENCES SUCURSAL, 
    PRIMARY KEY(codsucursal,idrevista)
    );

CREATE TABLE PERIODISTA(
	idperiodista 	number(4),
    nombre	varchar2(30),
    apellido varchar2(30),
    telefono	varchar2(10),
    especialidad	varchar2(30),
 	tiponacionalidadperiodista	varchar2(10),
    PRIMARY KEY (idperiodista)
    );
CREATE SEQUENCE secuenciaPeriodista START with 1 INCREMENT BY 1 maxvalue 99999999 minvalue 1;
CREATE TABLE Periodista_Escribe_Revista(
	idperiodista	number(4),
	idrevista	number(5),
	FOREIGN KEY (idperiodista) REFERENCES PERIODISTA,
	FOREIGN KEY (idrevista) REFERENCES REVISTA,
	PRIMARY key (idperiodista,idrevista)
	);

CREATE TABLE SECCION(
	idseccion	number(4),
	titulo	varchar2(30),
	descripcion	varchar2(30),
	idrevista number(5),
	FOREIGN KEY (idrevista) REFERENCES REVISTA,
	PRIMARY KEY (idseccion)
CREATE SEQUENCE secuenciaSeccion START with 1 INCREMENT BY 1 maxvalue 99999999 minvalue 1;
	);
CREATE TABLE EJEMPLAR(
	idejemplar	number(5),
	num_ejemplares	number(10), 
	numpaginas	number(3), 
	fecha	date, 
	idrevista	number(5),
	FOREIGN KEY (idrevista) REFERENCES REVISTA,
	PRIMARY KEY (idrevista)
	);
CREATE SEQUENCE secuenciaEjemplar START with 1 INCREMENT BY 1 maxvalue 99999999 minvalue 1;

 
INSERT INTO DUMMY.EMPRESASEGURIDAD (CIFSEGURIDAD) 
VALUES ('696969696969696'); 
INSERT  INTO DUMMY.GUARDIAS (IDGUARDIA,NOMBRE,APELLIDOS,CIFSEGURIDAD)
VALUES (SECUENCIAGUARDIAS.nextval,'Horse','Manuel','696969696969696');
INSERT  INTO DUMMY.GUARDIAS (IDGUARDIA,NOMBRE,APELLIDOS,CIFSEGURIDAD)
VALUES (SECUENCIAGUARDIAS.nextval,'Elsa','Pito','696969696969696');
INSERT INTO DUMMY.SUCURSAL (CODSUCURSAL,DIRECCION,TELEFONO,CIUDAD,PROVINCIA,CIFSEGURIDAD)
VALUES (SECUENCIASUCURSAL.nextval,'C/ SAN FRANCO','112','Keoland','YUCATAN','696969696969696');
INSERT INTO DUMMY.SUCURSAL (CODSUCURSAL,DIRECCION,TELEFONO,CIUDAD,PROVINCIA,CIFSEGURIDAD)
VALUES (SECUENCIASUCURSAL.nextval,'C/ SAN LUIS','115','Amores','BADALONA','696969696969696');
INSERT INTO DUMMY.SUCURSAL (CODSUCURSAL,DIRECCION,TELEFONO,CIUDAD,PROVINCIA,CIFSEGURIDAD)
VALUES (SECUENCIASUCURSAL.nextval,'C/ SAN FERNANDO','1231','Dos Hermanas','SEVILLA','696969696969696');
INSERT INTO DUMMY.EMPLEADO (IDTRABAJADOR ,NIF ,NOMBRE ,APELLIDO ,TELEFONO ,DIRECCION ,CODIGO_SUCURSAL)
VALUES (SECUENCIAEMPLEADO.nextval,'6543234Q','Jose','Ruiz','32312313','C/San Jordan',2);
INSERT INTO DUMMY.EMPLEADO (IDTRABAJADOR ,NIF ,NOMBRE ,APELLIDO ,TELEFONO ,DIRECCION ,CODIGO_SUCURSAL)
VALUES (SECUENCIAEMPLEADO.nextval,'6544234Q','Josefa','Ruiza','32312113','C/San Hot',1);
INSERT INTO DUMMY.EMPLEADO (IDTRABAJADOR ,NIF ,NOMBRE ,APELLIDO ,TELEFONO ,DIRECCION ,CODIGO_SUCURSAL)
VALUES (SECUENCIAEMPLEADO.nextval,'6544234Z','Josefina','Rasa','323121','C/San Haat',1);
INSERT INTO DUMMY.EMPLEADO (IDTRABAJADOR ,NIF ,NOMBRE ,APELLIDO ,TELEFONO ,DIRECCION ,CODIGO_SUCURSAL)
VALUES (SECUENCIAEMPLEADO.nextval,'8543212Q','Juan','Lemar','3265313','C/San Jon',2);
INSERT INTO DUMMY.REVISTA (IDREVISTA,TÍTULO,TIPO,PERIODICIDAD)
VALUES (SECUENCIAREVISTA.nextval,'Hola','Prensa Rosa',sysdate);
INSERT INTO DUMMY.REVISTA (IDREVISTA,TÍTULO,TIPO,PERIODICIDAD)
VALUES (SECUENCIAREVISTA.nextval,'Automotor','Motor',sysdate);
INSERT INTO DUMMY.REVISTA (IDREVISTA,TÍTULO,TIPO,PERIODICIDAD)
VALUES (SECUENCIAREVISTA.nextval,'HipHopNation','Musica',sysdate);
INSERT INTO DUMMY.REVISTA (IDREVISTA,TÍTULO,TIPO,PERIODICIDAD)
VALUES (SECUENCIAREVISTA.nextval,'REC','Paranormal',sysdate);
INSERT INTO DUMMY.REVISTA (IDREVISTA,TÍTULO,TIPO,PERIODICIDAD)
VALUES (SECUENCIAREVISTA.nextval,'Playboy','Adultos',sysdate);
INSERT INTO DUMMY.SUCURSALPUBLICAREVISTA (CODSUCURSAL,IDREVISTA)
VALUES (1,1);
INSERT INTO DUMMY.SUCURSALPUBLICAREVISTA (CODSUCURSAL,IDREVISTA)
VALUES (1,2);
INSERT INTO DUMMY.SUCURSALPUBLICAREVISTA (CODSUCURSAL,IDREVISTA)
VALUES (3,1);
INSERT INTO DUMMY.SUCURSALPUBLICAREVISTA (CODSUCURSAL,IDREVISTA)
VALUES (2,3);
INSERT INTO DUMMY.PERIODISTA  (IDPERIODISTA,NOMBRE,APELLIDO,TELEFONO,ESPECIALIDAD,TIPONACIONALIDADPERIODISTA)
VALUES (SECUENCIAPERIODISTA.nextval,'Manolo','Casquet','654342141','MOTOR','ESPANIA');
INSERT INTO DUMMY.PERIODISTA  (IDPERIODISTA,NOMBRE,APELLIDO,TELEFONO,ESPECIALIDAD,TIPONACIONALIDADPERIODISTA)
VALUES (SECUENCIAPERIODISTA.nextval,'Luck','Sack','954342141','Prensa Rosa','INGLATERRA');
INSERT INTO DUMMY.PERIODISTA  (IDPERIODISTA,NOMBRE,APELLIDO,TELEFONO,ESPECIALIDAD,TIPONACIONALIDADPERIODISTA)
VALUES (SECUENCIAPERIODISTA.nextval,'Nikobelic','Perst','764342141','MOTOR','ALBANIA');
INSERT INTO DUMMY.PERIODISTA  (IDPERIODISTA,NOMBRE,APELLIDO,TELEFONO,ESPECIALIDAD,TIPONACIONALIDADPERIODISTA)
VALUES (SECUENCIAPERIODISTA.nextval,'Manolo','Casquet','654342141','Adulto','ESPANIA');
INSERT INTO DUMMY.PERIODISTA_ESCRIBE_REVISTA (IDPERIODISTA ,IDREVISTA)
VALUES (4,1);
INSERT INTO DUMMY.PERIODISTA_ESCRIBE_REVISTA (IDPERIODISTA ,IDREVISTA)
VALUES (1,1);
INSERT INTO DUMMY.PERIODISTA_ESCRIBE_REVISTA (IDPERIODISTA ,IDREVISTA)
VALUES (3,2);
INSERT INTO DUMMY.SECCION (IDSECCION,TITULO,DESCRIPCION,IDREVISTA)
VALUES (12,'Lo mas Sexy de 2021','El mismo titulo lo dice',1);
INSERT INTO DUMMY.SECCION (IDSECCION,TITULO,DESCRIPCION,IDREVISTA)
VALUES (11,'El auto del mes','El mismo titulo lo dice',3);
INSERT INTO DUMMY.EJEMPLAR  (IDEJEMPLAR,NUM_EJEMPLARES,NUMPAGINAS,FECHA,IDREVISTA)
VALUES (1,1233213,30,sysdate,1);
INSERT INTO DUMMY.EJEMPLAR  (IDEJEMPLAR,NUM_EJEMPLARES,NUMPAGINAS,FECHA,IDREVISTA)
VALUES (22,33213,27,sysdate,3);
INSERT INTO DUMMY.EJEMPLAR  (IDEJEMPLAR,NUM_EJEMPLARES,NUMPAGINAS,FECHA,IDREVISTA)
VALUES (3,99999,21,sysdate,4);
INSERT INTO DUMMY.EJEMPLAR  (IDEJEMPLAR,NUM_EJEMPLARES,NUMPAGINAS,FECHA,IDREVISTA)
VALUES (12,33213,27,sysdate,2);