DROP TABLE ACTUA;
DROP TABLE ALQUILA;
DROP TABLE ACTORES;
DROP TABLE SOCIO;
DROP TABLE EJEMPLAR;
DROP TABLE PELICULA;
DROP TABLE DIRECTOR;
CREATE TABLE DIRECTOR (
  NOMBRE       VARCHAR2(40),
  PRIMARY KEY (NOMBRE),
  NACIONALIDAD VARCHAR2(40)
);
CREATE TABLE PELICULA(
ID           NUMBER        CONSTRAINT pkpelicula PRIMARY KEY,
TITULO       VARCHAR2(40),
PRODUCTORA   VARCHAR2(40),
NACIONALIDAD VARCHAR2(40),
FECHA        DATE,
DIRECTOR     VARCHAR2(40)  CONSTRAINT fkdirector REFERENCES DIRECTOR(NOMBRE)
);
CREATE TABLE EJEMPLAR(
IDPELICULA NUMBER,
NUMERO     NUMBER(2),
ESTADO     VARCHAR2(40),
CONSTRAINT pkejemplar PRIMARY KEY(IDPELICULA, NUMERO),
CONSTRAINT fkejemplar FOREIGN KEY(IDPELICULA) REFERENCES PELICULA(ID)
);

CREATE TABLE SOCIO(
  DNI       VARCHAR2(9),
  NOMBRE    VARCHAR2(30) CONSTRAINT nombrenonulo NOT NULL,
  DIRECCION VARCHAR2(30),
  TELEFONO  VARCHAR2(10),
  AVALADOR  VARCHAR2(10),
PRIMARY KEY(DNI),
  CONSTRAINT fksocio FOREIGN KEY(AVALADOR) REFERENCES SOCIO(DNI)
);
CREATE TABLE ACTORES
(
  NOMBRE       VARCHAR2(30),
  NACIONALIDAD VARCHAR2(30),
  SEXO         VARCHAR2(1),
  CONSTRAINT pkactores PRIMARY KEY(NOMBRE),
  CONSTRAINT checksexo    CHECK (SEXO IN ('H', 'M'))
);

CREATE TABLE ACTUA(
ACTOR        VARCHAR2(30),
IDPELICULA   NUMBER,
PROTAGONISTA VARCHAR2(1) DEFAULT 'N',
CONSTRAINT pkactua PRIMARY KEY(ACTOR, IDPELICULA),
CONSTRAINT checkprotagonista CHECK (PROTAGONISTA IN ('N', 'S'))
);
CREATE TABLE ALQUILA(
DNI              CHAR(9),
IDPELICULA       NUMBER,
NUMERO           NUMBER(2),
FECHA_ALQUILER   DATE,
FECHA_DEVOLUCION DATE,
CONSTRAINT pkalquila PRIMARY KEY(DNI, IDPELICULA, NUMERO, FECHA_ALQUILER),
CONSTRAINT fk1dni    FOREIGN KEY(DNI) REFERENCES SOCIO(DNI),
CONSTRAINT fk2peli   FOREIGN KEY(IDPELICULA, NUMERO) REFERENCES EJEMPLAR(IDPELICULA, NUMERO),
CONSTRAINT checkfechas  CHECK (FECHA_DEVOLUCION > FECHA_ALQUILER)
);		